dist: bionic

language: go

go_import_path: github.com/cntmio/cntmology

os:
  - linux
  - osx

go:
  - 1.17.x

script:
    - bash ./.travis.script.bash
    - bash ./.travis.deploy.bash

deploy:
  provider: releases
  token: "${GITHUB_TOKEN}"
  file_glob: true
  file:
    - cntmology*
    - tool-*.zip
  skip_cleanup: true
  overwrite: true
  draft: true
  on:
    tags: true
