language: go

install:
  - grep 'import' -rl ./| grep ".go"| xargs sed -i 's#"github.com/Ontology/#"github.com/Ontology/Ontology/#g'
  - go get github.com/Masterminds/glide
  - glide install

go:
  - 1.8.x
